import type { User, Experience, Booking, Review, UserRewards, HostAnalytics } from "./types"

// Mock Users
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john.doe@example.com",
    name: "John Doe",
    avatar: "/profile-photo-man.png",
    role: "user",
    phone: "+1-555-0123",
    bio: "Adventure enthusiast who loves exploring new places and trying extreme sports.",
    location: "San Francisco, CA",
    joinedAt: new Date("2023-01-15"),
    isVerified: true,
    preferences: {
      categories: ["hiking", "climbing", "water-sports"],
      priceRange: [50, 300],
      difficulty: ["intermediate", "advanced"],
    },
    stats: {
      totalBookings: 12,
      totalSpent: 2400,
      reviewsGiven: 10,
    },
  },
  {
    id: "host-1",
    email: "sarah.wilson@example.com",
    name: "Sarah Wilson",
    avatar: "/profile-photo-woman.png",
    role: "host",
    phone: "+1-555-0456",
    bio: "Professional mountain guide with 10+ years of experience leading adventures.",
    location: "Denver, CO",
    joinedAt: new Date("2022-06-10"),
    isVerified: true,
    preferences: {
      categories: ["hiking", "climbing"],
      priceRange: [100, 500],
      difficulty: ["beginner", "intermediate", "advanced"],
    },
    stats: {
      totalBookings: 156,
      totalSpent: 0,
      reviewsGiven: 45,
    },
  },
  {
    id: "admin-1",
    email: "admin@xhunt.com",
    name: "Admin User",
    avatar: "/admin-profile.png",
    role: "admin",
    location: "New York, NY",
    joinedAt: new Date("2022-01-01"),
    isVerified: true,
    preferences: {
      categories: [],
      priceRange: [0, 1000],
      difficulty: [],
    },
    stats: {
      totalBookings: 0,
      totalSpent: 0,
      reviewsGiven: 0,
    },
  },
]

// Mock Experiences
export const mockExperiences: Experience[] = [
  {
    id: "exp-1",
    title: "Epic Mountain Hiking Adventure",
    description:
      "Join us for an unforgettable hiking experience through pristine mountain trails. This full-day adventure takes you through diverse landscapes, from dense forests to alpine meadows, culminating in breathtaking summit views. Perfect for intermediate hikers looking to challenge themselves while enjoying nature's beauty.",
    shortDescription: "Full-day mountain hiking with stunning summit views",
    category: "hiking",
    location: {
      city: "Aspen",
      country: "USA",
      coordinates: [39.1911, -106.8175],
      address: "Maroon Bells Scenic Area, Aspen, CO",
    },
    pricing: {
      basePrice: 120,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 2, max: 8 },
    },
    duration: { hours: 8 },
    difficulty: "intermediate",
    images: ["/mountain-hiking-trail.png", "/alpine-lake-view.png", "/summit-panorama.png"],
    hostId: "host-1",
    rating: 4.8,
    reviewCount: 24,
    features: ["Professional Guide", "Small Groups", "Photo Opportunities", "Wildlife Spotting"],
    included: ["Professional guide", "Safety equipment", "Trail snacks", "Water bottle"],
    requirements: ["Moderate fitness level", "Hiking boots", "Weather-appropriate clothing"],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience",
    availability: {
      startDate: new Date("2024-04-01"),
      endDate: new Date("2024-10-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "exp-2",
    title: "Rock Climbing for Beginners",
    description:
      "Perfect introduction to rock climbing in a safe, controlled environment. Our certified instructors will teach you fundamental techniques, safety procedures, and help you build confidence on the rock. All equipment provided.",
    shortDescription: "Learn rock climbing basics with certified instructors",
    category: "climbing",
    location: {
      city: "Joshua Tree",
      country: "USA",
      coordinates: [33.8734, -115.901],
      address: "Joshua Tree National Park, CA",
    },
    pricing: {
      basePrice: 95,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 1, max: 4 },
    },
    duration: { hours: 4 },
    difficulty: "beginner",
    images: ["/rock-climbing-instruction.png", "/placeholder-qrgfb.png", "/joshua-tree-rocks.png"],
    hostId: "host-1",
    rating: 4.9,
    reviewCount: 18,
    features: ["Beginner Friendly", "All Equipment Included", "Certified Instructor", "Safety First"],
    included: ["Climbing gear", "Helmet", "Harness", "Instruction", "Safety briefing"],
    requirements: ["No experience needed", "Comfortable athletic clothing", "Closed-toe shoes"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience",
    availability: {
      startDate: new Date("2024-03-01"),
      endDate: new Date("2024-11-30"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "exp-3",
    title: "Whitewater Rafting Extreme",
    description:
      "Experience the thrill of Class IV rapids on this adrenaline-pumping whitewater rafting adventure. Navigate through challenging rapids while enjoying spectacular canyon scenery. For experienced rafters only.",
    shortDescription: "Extreme whitewater rafting through Class IV rapids",
    category: "water-sports",
    location: {
      city: "Moab",
      country: "USA",
      coordinates: [38.5733, -109.5498],
      address: "Colorado River, Moab, UT",
    },
    pricing: {
      basePrice: 180,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 4, max: 12 },
    },
    duration: { hours: 6 },
    difficulty: "expert",
    images: [
      "/placeholder-a4e3u.png",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hostId: "host-1",
    rating: 4.7,
    reviewCount: 31,
    features: ["Expert Guides", "Class IV Rapids", "Canyon Views", "Adrenaline Rush"],
    included: ["Professional guide", "Safety equipment", "Wetsuit", "Lunch", "Transportation"],
    requirements: ["Previous rafting experience", "Strong swimming ability", "Age 18+"],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience",
    availability: {
      startDate: new Date("2024-05-01"),
      endDate: new Date("2024-09-30"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "exp-4",
    title: "Accessible City Garden Tour",
    description:
      "Wheelchair-accessible botanical garden tour featuring sensory experiences, tactile plants, and audio descriptions. Designed for visitors with mobility challenges and visual impairments.",
    shortDescription: "Fully accessible botanical garden experience with sensory elements",
    category: "accessible",
    location: {
      city: "Portland",
      country: "USA",
      coordinates: [45.5152, -122.6784],
      address: "Portland Japanese Garden, Portland, OR",
    },
    pricing: {
      basePrice: 35,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 1, max: 12 },
    },
    duration: { hours: 2 },
    difficulty: "beginner",
    images: ["/accessible-garden-tour.png", "/wheelchair-accessible-path.png", "/sensory-garden.png"],
    hostId: "host-1",
    rating: 4.9,
    reviewCount: 42,
    features: ["Wheelchair Accessible", "Audio Descriptions", "Sensory Experience", "Professional Guide"],
    included: ["Accessibility equipment", "Audio guide", "Tactile materials", "Rest stops"],
    requirements: ["No physical requirements", "All abilities welcome"],
    cancellationPolicy: "Free cancellation up to 24 hours before",
    availability: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-12-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "exp-5",
    title: "Family Treasure Hunt Adventure",
    description:
      "Interactive city-wide treasure hunt perfect for families with children ages 5-15. Solve puzzles, discover local history, and work together to find hidden treasures throughout the downtown area.",
    shortDescription: "Interactive family treasure hunt through the city",
    category: "family-friendly",
    location: {
      city: "Austin",
      country: "USA",
      coordinates: [30.2672, -97.7431],
      address: "Downtown Austin, TX",
    },
    pricing: {
      basePrice: 25,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 2, max: 8 },
    },
    duration: { hours: 3 },
    difficulty: "beginner",
    images: ["/family-treasure-hunt.png", "/children-solving-puzzles.png", "/downtown-austin-skyline.png"],
    hostId: "host-1",
    rating: 4.7,
    reviewCount: 89,
    features: ["Kid-Friendly", "Educational", "Interactive", "City Exploration"],
    included: ["Treasure map", "Puzzle clues", "Small prizes", "Photo opportunities"],
    requirements: ["Ages 5+", "Comfortable walking shoes", "Smartphone for clues"],
    cancellationPolicy: "Free cancellation up to 12 hours before",
    availability: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-12-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "exp-6",
    title: "Mindful Forest Bathing",
    description:
      "Therapeutic wellness experience combining meditation, gentle movement, and nature immersion. Perfect for stress relief and mental wellness. Suitable for all fitness levels and ages 16+.",
    shortDescription: "Therapeutic forest bathing and mindfulness experience",
    category: "wellness",
    location: {
      city: "Sedona",
      country: "USA",
      coordinates: [34.8697, -111.761],
      address: "Red Rock State Park, Sedona, AZ",
    },
    pricing: {
      basePrice: 65,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 1, max: 10 },
    },
    duration: { hours: 2.5 },
    difficulty: "beginner",
    images: ["/forest-meditation.png", "/sedona-red-rocks.png", "/mindfulness-nature.png"],
    hostId: "host-1",
    rating: 4.8,
    reviewCount: 67,
    features: ["Stress Relief", "All Levels Welcome", "Certified Instructor", "Mental Wellness"],
    included: ["Meditation guidance", "Yoga mat", "Herbal tea", "Relaxation techniques"],
    requirements: ["Comfortable clothing", "Open mind", "Ages 16+"],
    cancellationPolicy: "Free cancellation up to 24 hours before",
    availability: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-12-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-01-30"),
  },
  {
    id: "exp-7",
    title: "Senior-Friendly Historic Walking Tour",
    description:
      "Gentle-paced historic district tour with frequent rest stops, comfortable seating, and fascinating local stories. Designed specifically for seniors and those preferring a relaxed pace.",
    shortDescription: "Relaxed historic tour perfect for seniors",
    category: "senior-friendly",
    location: {
      city: "Charleston",
      country: "USA",
      coordinates: [32.7767, -79.9311],
      address: "Historic Charleston, SC",
    },
    pricing: {
      basePrice: 30,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 2, max: 15 },
    },
    duration: { hours: 2 },
    difficulty: "beginner",
    images: ["/charleston-historic-district.png", "/senior-group-tour.png", "/historic-architecture.png"],
    hostId: "host-1",
    rating: 4.9,
    reviewCount: 156,
    features: ["Senior-Friendly", "Frequent Rest Stops", "Local History", "Comfortable Pace"],
    included: ["Professional guide", "Seating at stops", "Historical materials", "Water"],
    requirements: ["Comfortable walking shoes", "Sun protection", "Ages 55+"],
    cancellationPolicy: "Free cancellation up to 24 hours before",
    availability: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-12-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "exp-8",
    title: "Urban Street Art Workshop",
    description:
      "Learn legal street art techniques from local artists in designated graffiti zones. Create your own masterpiece while exploring urban culture and artistic expression.",
    shortDescription: "Hands-on street art workshop with local artists",
    category: "art-creative",
    location: {
      city: "Miami",
      country: "USA",
      coordinates: [25.7617, -80.1918],
      address: "Wynwood Arts District, Miami, FL",
    },
    pricing: {
      basePrice: 85,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 3, max: 8 },
    },
    duration: { hours: 4 },
    difficulty: "beginner",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hostId: "host-1",
    rating: 4.6,
    reviewCount: 73,
    features: ["Local Artists", "All Materials Included", "Legal Walls", "Creative Expression"],
    included: ["Art supplies", "Spray paint", "Protective gear", "Artist instruction"],
    requirements: ["No experience needed", "Old clothes recommended", "Ages 14+"],
    cancellationPolicy: "Free cancellation up to 48 hours before",
    availability: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-12-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "exp-9",
    title: "Community Garden Volunteer Experience",
    description:
      "Give back to the community while learning sustainable gardening practices. Help maintain local food gardens that serve underprivileged families while connecting with like-minded volunteers.",
    shortDescription: "Meaningful volunteer work in community gardens",
    category: "volunteer",
    location: {
      city: "Seattle",
      country: "USA",
      coordinates: [47.6062, -122.3321],
      address: "Community Gardens, Seattle, WA",
    },
    pricing: {
      basePrice: 0,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 1, max: 20 },
    },
    duration: { hours: 3 },
    difficulty: "beginner",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hostId: "host-1",
    rating: 4.8,
    reviewCount: 124,
    features: ["Social Impact", "Learn Gardening", "Community Connection", "Free Experience"],
    included: ["Gardening tools", "Gloves", "Instructions", "Refreshments"],
    requirements: ["Comfortable work clothes", "Sun protection", "Ages 12+"],
    cancellationPolicy: "Free cancellation up to 12 hours before",
    availability: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-12-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "exp-10",
    title: "Couples Sunset Wine Tasting",
    description:
      "Romantic wine tasting experience overlooking vineyard landscapes at golden hour. Perfect for date nights, anniversaries, or proposals. Includes premium wines and artisanal cheese pairings.",
    shortDescription: "Romantic sunset wine tasting for couples",
    category: "romantic",
    location: {
      city: "Napa Valley",
      country: "USA",
      coordinates: [38.2975, -122.2869],
      address: "Napa Valley Vineyards, CA",
    },
    pricing: {
      basePrice: 150,
      currency: "USD",
      priceType: "per_person",
      groupSize: { min: 2, max: 8 },
    },
    duration: { hours: 3 },
    difficulty: "beginner",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hostId: "host-1",
    rating: 4.9,
    reviewCount: 98,
    features: ["Romantic Setting", "Premium Wines", "Sunset Views", "Couples Experience"],
    included: ["Wine tastings", "Cheese pairings", "Sunset viewing", "Souvenir glasses"],
    requirements: ["Ages 21+", "Valid ID required", "Smart casual attire"],
    cancellationPolicy: "Free cancellation up to 48 hours before",
    availability: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-12-31"),
      blackoutDates: [],
    },
    isActive: true,
    createdAt: new Date("2024-02-14"),
    updatedAt: new Date("2024-02-14"),
  },
]

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: "booking-1",
    userId: "user-1",
    experienceId: "exp-1",
    hostId: "host-1",
    status: "confirmed",
    bookingDate: new Date("2024-02-15"),
    experienceDate: new Date("2024-03-20"),
    participants: { adults: 2, children: 0, infants: 0 },
    totalAmount: 240,
    currency: "USD",
    paymentStatus: "paid",
    paymentMethod: "credit_card",
    contactInfo: {
      name: "John Doe",
      email: "john.doe@example.com",
      phone: "+1-555-0123",
    },
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
]

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: "review-1",
    bookingId: "booking-1",
    userId: "user-1",
    experienceId: "exp-1",
    rating: 5,
    title: "Amazing mountain adventure!",
    comment:
      "Sarah was an incredible guide. The views were breathtaking and the entire experience exceeded my expectations. Highly recommend!",
    helpfulVotes: 8,
    createdAt: new Date("2024-03-22"),
    response: {
      comment: "Thank you so much for the wonderful review! It was a pleasure having you on the trail.",
      createdAt: new Date("2024-03-23"),
    },
  },
]

// Mock User Rewards
export const mockUserRewards: UserRewards[] = [
  {
    userId: "user-1",
    points: 1250,
    level: 3,
    badges: [
      {
        id: "badge-1",
        name: "First Adventure",
        description: "Completed your first X-hunt experience",
        icon: "🎯",
        rarity: "common",
        earnedAt: new Date("2023-02-01"),
      },
      {
        id: "badge-2",
        name: "Mountain Explorer",
        description: "Completed 5 hiking experiences",
        icon: "⛰️",
        rarity: "rare",
        earnedAt: new Date("2023-08-15"),
      },
    ],
    achievements: [
      {
        id: "achievement-1",
        name: "Adventure Seeker",
        description: "Book 10 different experiences",
        progress: 7,
        target: 10,
        isCompleted: false,
        reward: { points: 500, badge: "adventure-seeker" },
      },
    ],
    streaks: {
      currentBookingStreak: 3,
      longestBookingStreak: 5,
      lastBookingDate: new Date("2024-02-15"),
    },
  },
]

export const mockRewards = mockUserRewards[0] // Default to first user's rewards

// Mock Host Analytics
export const mockHostAnalytics: HostAnalytics[] = [
  {
    hostId: "host-1",
    period: {
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-02-29"),
    },
    metrics: {
      totalBookings: 45,
      totalRevenue: 8750,
      averageRating: 4.8,
      responseRate: 98,
      cancellationRate: 2,
      repeatCustomers: 12,
    },
    topExperiences: [
      {
        experienceId: "exp-1",
        bookings: 24,
        revenue: 2880,
      },
      {
        experienceId: "exp-2",
        bookings: 18,
        revenue: 1710,
      },
    ],
    monthlyData: [
      { month: "January", bookings: 22, revenue: 4200 },
      { month: "February", bookings: 23, revenue: 4550 },
    ],
  },
]
